#!/bin/bash
COLOR_DEPTH=16
RESOLUTION=1792x1008
HOST=$1
USER=
PASSWORD=
MOUNT=disk:UB=$HOME/windows
DOMAIN=UCLAB

rdesktop -u "$USER" -p "$PASSWORD" -d "$DOMAIN" -a "$COLOR_DEPTH" -g "$RESOLUTION" -r "$MOUNT" -r clipboard:CLIPBOARD "$HOST";
