#!/bin/bash


command="pushd '{}/..'; \"$@\"; popd >/dev/null"
find . -maxdepth 8 -type d -exec test -d {}/.svn \; -prune -print0 | sort -z | xargs -0 -n 1 -I {} bash -c 'cd "$0" && echo "$0 - $*" && "$@"' '{}' "$@"
#| xargs -0 -n 1 -I '{}' bash -c "$command" "-" "$@"

